### ISSUE TITLE
applyChangeset does not ignore meta tables

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/geodiff#138]
In sqlite driver, we should be ignoring any changes to `gkg_*` tables - we ignore them already when creating changesets, but older versions of geodiff include them in the changesets.

Because of this, currently we sometimes get conflicts when trying to update a geopackage with diff from pre-1.0 geodiff using a new version of geodiff - for example, gpkg_contents table should have last modified date/time updated, but the "old" value in diff does not match the current value.

**Comment by wonder-sk** [comment]
Downstream issue: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/279

**Comment by PeterPetrik** [comment]
Is it fixing the downstream issue too, or just partially fixing it?

**Comment by wonder-sk** [comment]
> Is it fixing the downstream issue too, or just partially fixing it?

It should completely fix it, I will close the downstream ticket separately when upgrading to newer pygeodiff / mergin-client
