### ISSUE TITLE
Packaging for Python 3.10

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/geodiff#158]
Python 3.10 has been released, it would be good to add pygeodiff packages for 3.10 - otherwise the module will fail to install through pip if people don't have full MSVC environment.

**Comment by PeterPetrik** [comment]
this is for new OSGeo4W installations?

**Comment by wonder-sk** [comment]
No, OSGeo4W is still at python 3.9.x, but if someone installs Python on Windows (without QGIS/osgeo4w), the default version offered is python 3.10 and pip will fail to install pygeodiff in such setup.

**Comment by PeterPetrik** [comment]
```
  File "Python\Python310\site-packages\dateutil\parser.py", line 587, in parse
    if (isinstance(tzinfos, collections.Callable) or
AttributeError: module 'collections' has no attribute 'Callable'
```
