### ISSUE TITLE
QGIS Plugin

### ISSUE THREAD

**Issue by ffinger** [lutraconsulting/geodiff#159]
It would be great to create a plugin to make geodiff available to the general user within QGIS

**Comment by saberraz** [comment]
We already have a python client https://github.com/lutraconsulting/mergin-py-client and a plugin https://github.com/lutraconsulting/qgis-mergin-plugin

**Comment by ffinger** [comment]
I was thinking about a plugin or function with in QGIS to specifically use geodiff on local files, not synchronizing with mergin.
Or, at the minimum, adding an example of how to use geodiff from within QGIS (python console).

**Comment by PeterPetrik** [comment]
From QGIS' python console

```
import Mergin.mergin as mergin
help(mergin.MerginClient)
```
following with any function you would like to trigger, e.g. download as 
https://github.com/lutraconsulting/mergin-py-client#using-python-api

or for geodiff directly

```
import Mergin.mergin.deps.pygeodiff as pygeodiff
```

following by any command from here: https://github.com/lutraconsulting/geodiff#using-python-module
