### ISSUE TITLE
High-level rebase function

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/geodiff#22]
Currently the client on 'pull' needs to do a bunch of calls to geodiff.

local = gpkg in project directory - may be locally modified (based on v1)
base = gpkg in a side directory - keeps original data (v1)
server = gpkg in a side directory - has 'base' contents with changes from someone else (v2)

diff_server = server - base
diff_local = local - base

If the client wants to avoid copying of gpkg files (which may cause issues with WAL), these changesets need to be applied to local:

1. undo local changes `local += inversed( diff_local )`
2. add changes from server `local += diff_server`
3. add rebased local changes `local += rebased( diff_local, base, diff_server )`

It would be useful to have all this functionality contained in a single function call of geodiff:
rebase( base [gpkg], local [gpkg], server [gpkg] )
This would update 'local' as needed.

**Comment by wonder-sk** [comment]
Currently the python client does something like this:

```python
# "src" is the gpkg with the most recent server version

# temporary backup of file pulled from server for test and recovery
shutil.copy(src, f_server_backup)  
self.geodiff.create_changeset(base, src, server_diff)
self.geodiff.create_rebased_changeset(base, local, server_diff, rebased_diff)
# update file with rebased_diff to contain both server and local changes
self.geodiff.apply_changeset(src, rebased_diff)
# we are happy with rebase, prepare 'live' versions of files
shutil.copy(f_server_backup, base)
shutil.copy(src, local)
```

The main problem is that that the "local" file gets overwritten in the last step. If it is open and there would be changes in the WAL file not yet committed to .gpkg, we may loose data.

**Comment by PeterPetrik** [comment]
@wonder-sk isn't the solution  just to remove local* files instead of local file. WAL file is already considered in rebase, no?
