### ISSUE TITLE
Error when creating changeset if path contains a single quote

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/geodiff#74]
Looks like we need to escape the path properly:

SQLITE3: (1)near "s": syntax error in "ATTACH 'C:\Users\User\Documents\Martin's stuff\My Project\.mergin\phaseOne.gpkg' AS aux"

**Comment by PeterPetrik** [comment]
related to https://github.com/lutraconsulting/geodiff/issues/52

**Comment by tomasMizera** [comment]
Seems to be again windows specific issue. Did this happen to you @wonder-sk on linux?

**Comment by wonder-sk** [comment]
I haven't tried that on linux... but my assumption was that on linux it may be failing as well as we don't escape the quote...
